name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cabal:
    name: ${{ matrix.os }} - GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # Check the haddock step below which is limited to a single GHC version!
        ghc:
          - '9.12'
          - '9.10'
          - '9.8'
          # - '9.6'
          # - '9.4'
          # - '9.2'
          # - '9.0'
          # - '8.10'
          # - '8.8'
          # - '8.6'
          - '8.4'
          # hsc2hs fails on windows-2022 for GHCs 8.0 and 8.2
          # https://github.com/haskell/hsc2hs/issues/81
          # - '8.2'
          # - '8.0'
        include:
          - os: macos-latest
            ghc: '9.12'
          - os: ubuntu-latest
            ghc: '9.12'

    steps:
    - uses: actions/checkout@v4

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      id:   setup
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Configure
      run: |
        cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
        cabal build all --dry-run

    - name: Restore cache
      uses: actions/cache/restore@v4
      id:   cache
      with:
        path: ${{ steps.setup.outputs.cabal-store }}
        key:  ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-plan-${{ hashfiles('dist-newstyle/cache/plan.json') }}
        restore-keys: |
              ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-

    - name: Build dependencies
      run: cabal build all --dependencies-only

    - run: cabal build all
    - run: cabal test all
    - run: cabal haddock
      if:  matrix.ghc == '9.12'
    - run: cabal check
    - run: cabal sdist

    - name: Save cache
      uses: actions/cache/save@v4
      if:   always() && steps.cache.outputs.cache-hit != 'true'
      with:
        key:  ${{ steps.cache.outputs.cache-primary-key }}
        path: ${{ steps.setup.outputs.cabal-store }}
